name = "Conventional Logs"
license = "MIT"
description = "Hugo theme for Conventional Logs website"
homepage = "https://github.com/lorenzodianni/hugo-conventional-logs-theme"
tags = []
features = []
min_version = "0.42"
